// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Cbzwoagw4w9TuRRZ1Z-_1J5cJtLR38o',
    appId: '1:661572628111:web:abe8edcbc0e59d7f8a8afa',
    messagingSenderId: '661572628111',
    projectId: 'midwiferyhospital',
    authDomain: 'midwiferyhospital.firebaseapp.com',
    storageBucket: 'midwiferyhospital.firebasestorage.app',
    measurementId: 'G-Y5KKH023ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5QAEDzQj1mfFkiZ_jbpsiwdDF1dE0SsA',
    appId: '1:661572628111:android:0ad84048ad16ec0f8a8afa',
    messagingSenderId: '661572628111',
    projectId: 'midwiferyhospital',
    storageBucket: 'midwiferyhospital.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeRqjD2v7Qwzg4SZqn7surNotWXMuoFAc',
    appId: '1:661572628111:ios:3b00684724f3b7478a8afa',
    messagingSenderId: '661572628111',
    projectId: 'midwiferyhospital',
    storageBucket: 'midwiferyhospital.firebasestorage.app',
    iosBundleId: 'com.example.hospital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeRqjD2v7Qwzg4SZqn7surNotWXMuoFAc',
    appId: '1:661572628111:ios:3b00684724f3b7478a8afa',
    messagingSenderId: '661572628111',
    projectId: 'midwiferyhospital',
    storageBucket: 'midwiferyhospital.firebasestorage.app',
    iosBundleId: 'com.example.hospital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_Cbzwoagw4w9TuRRZ1Z-_1J5cJtLR38o',
    appId: '1:661572628111:web:92d99a2147c423778a8afa',
    messagingSenderId: '661572628111',
    projectId: 'midwiferyhospital',
    authDomain: 'midwiferyhospital.firebaseapp.com',
    storageBucket: 'midwiferyhospital.firebasestorage.app',
    measurementId: 'G-DZ5T8DQKPY',
  );
}
